from dotenv import load_dotenv
import os

load_dotenv()

# DETECTION設定
DETECTION_MODEL = os.getenv("DETECTION_MODEL")
DETECTION_IMG_SIZE = int(os.getenv("DETECTION_IMG_SIZE"))
DETECTION_CONFIDENCE = float(os.getenv("DETECTION_CONFIDENCE"))
DETECTION_IOU = float(os.getenv("DETECTION_IOU"))
DETECTION_SAVE = False
DETECTION_TARGET_WIDTH = int(os.getenv("DETECTION_TARGET_WIDTH"))
DETECTION_TARGET_HEIGHT = int(os.getenv("DETECTION_TARGET_HEIGHT"))

# OCR設定
OCR_MODEL = os.getenv("OCR_MODEL")
OCR_IMG_SIZE = int(os.getenv("OCR_IMG_SIZE"))
OCR_CONFIDENCE = float(os.getenv("OCR_CONFIDENCE"))
OCR_IOU = float(os.getenv("OCR_IOU"))
OCR_SAVE = False
OCR_START_REGION_CODE_CLASS_ID = int(os.getenv("OCR_START_REGION_CODE_CLASS_ID"))
UNDEFINED_TEXT = os.getenv("UNDEFINED_TEXT")

# OUTPUT設定
OUTPUT_CAPTURE_DIR = os.getenv("OUTPUT_CAPTURE_DIR")
OUTPUT_DETECT_DIR = os.getenv("OUTPUT_DETECT_DIR")
OUTPUT_LOGS_DIR = os.getenv("OUTPUT_LOGS_DIR")

# RPI CAM設定
CAMERA_ID = os.getenv("CAMERA_ID")
RPICAM_METERING = os.getenv("RPICAM_METERING")
RPICAM_AUTOFOCUS_MODE = os.getenv("RPICAM_AUTOFOCUS_MODE")
RPICAM_TIMEOUT = int(os.getenv("RPICAM_TIMEOUT"))

# TIME STAMP設定
TIME_STAMP_FORMAT = os.getenv("TIME_STAMP_FORMAT")
