from enum import Enum, auto

class Attraction(Enum):
    BALLOON_RACE = "バルーンレース"
    MEGA_COASTER = "メガコースター"
    HIDE_AND_SEEK_WITH_BAKKE = "ばっけとかくれんぼ"
    GURURI_FOREST = "ぐるり森"
    KURUKURU_CRUISE = "くるくるクルーズ"
    MINI_COASTER = "ミニコースター"
    MINI_Q_RACING = "ミニQレーシング"
    BLOCK_CART = "ブロックカート"
    LOG_RIDE = "急流すべり"
    DETEMIYA = "デテミーヤ"
    POPCORN_PANIC = "ポップコーンパニック"
    DRAGON_FIGHTER = "ドラゴンファイター"
    MAWATTAWA = "まわったわー"
    GOOD_JOB_OPERATION = "グッジョブ大作戦"
    PALPAL_STADIUM = "パルパルスタジアム"
    MERRY_GO_ROUND = "メリーゴーランド"
    FOUR_D_THEATER = "4Dシアター"
    TOMATORE = "トマトーレ"
    PIRATE_SHIP = "海賊船"
    HANGING_OUT_DUCKS = "おでかけダックス"
    FERRIS_WHEEL = "観覧車"
    DONGURINO = "どんぐりーの"
    PALKKIO = "パルッキオ"
    WILD_STORM = "ワイルドストーム"
    PARACHUTE_TOWER = "パラシュートタワー"
    