from dotenv import load_dotenv
import os

load_dotenv()

# OUTPUT設定
OUTPUT_LOGS_DIR = os.getenv("OUTPUT_LOGS_DIR")
OUTPUT_BUFFER_DIR = os.getenv("OUTPUT_BUFFER_DIR")
ERROR_LOG_FILE_NAME = os.getenv("ERROR_LOG_FILE_NAME")
BUFFER_JSON_FILE_NAME = os.getenv("BUFFER_JSON_FILE_NAME")

# TIME STAMP設定
TIME_STAMP_DB_FORMAT = os.getenv("TIME_STAMP_DB_FORMAT")
TIME_STAMP_LOCAL_FORMAT = os.getenv("TIME_STAMP_LOCAL_FORMAT")

# PROXIMITY SENSOR設定
PROXIMITY_SENSOR_THRESHOLD_CM = float(os.getenv("PROXIMITY_SENSOR_THRESHOLD_CM"))
PROXIMITY_SENSOR_TRIGGER_PIN = int(os.getenv("PROXIMITY_SENSOR_TRIGGER_PIN"))
PROXIMITY_SENSOR_ECHO_PIN = int(os.getenv("PROXIMITY_SENSOR_ECHO_PIN"))
PROXIMITY_SENSOR_MAX_DISTANCE_METER = float(os.getenv("PROXIMITY_SENSOR_MAX_DISTANCE_METER"))
PROXIMITY_SENSOR_OUT_OF_RANGE = os.getenv("PROXIMITY_SENSOR_OUT_OF_RANGE")

# DATABASE設定
API_DATA_URL = os.getenv("API_DATA_URL")
API_KEY = os.getenv("API_KEY")
API_NAME = os.getenv("API_NAME")
DB_TIMEOUT_SEC = float(os.getenv("DB_TIMEOUT_SEC"))

# MAIN設定
MAIN_LOOP_DELAY_SEC = float(os.getenv("MAIN_LOOP_DELAY_SEC"))