import os
from dotenv import load_dotenv

load_dotenv()

# DATABASE設定
DATABASE_URL = os.getenv("DATABASE_URL")
API_KEY = os.getenv("API_KEY")

# TIMESTAMP設定
TIME_STAMP_FORMAT = os.getenv("TIME_STAMP_FORMAT")

# ATTRACTION STATUS設定
ATTRACTION_STATUS_RUNNING = os.getenv("ATTRACTION_STATUS_RUNNING") # 運行
ATTRACTION_STATUS_INSPECTION = os.getenv("ATTRACTION_STATUS_INSPECTION") # 点検
ATTRACTION_STATUS_SUSPENDED = os.getenv("ATTRACTION_STATUS_SUSPENDED") # 休止
ATTRACTION_STATUS_RAIN = os.getenv("ATTRACTION_STATUS_RAIN") # 雨天
ATTRACTION_STATUS_THUNDER = os.getenv("ATTRACTION_STATUS_THUNDER") # 雷
ATTRACTION_STATUS_STRONG_WIND = os.getenv("ATTRACTION_STATUS_STRONG_WIND") # 強風
ATTRACTION_STATUS_EARLY_CLOSE = os.getenv("ATTRACTION_STATUS_EARLY_CLOSE") # 繰上
ATTRACTION_STATUS_BAD_WEATHER = os.getenv("ATTRACTION_STATUS_BAD_WEATHER") # 悪天

# ATTRACTION WAITING TIME設定
ATTRACTION_WAITING_TIME_ERROR = os.getenv("ATTRACTION_WAITING_TIME_ERROR")

# REGION CODE SETTINGS
UNDEFINED_TEXT = os.getenv("UNDEFINED_TEXT")
