import os
from dotenv import load_dotenv

load_dotenv()

# DETECTION設定
DETECTION_MODEL = os.getenv("DETECTION_MODEL")
DETECTION_IMG_SIZE = int(os.getenv("DETECTION_IMG_SIZE"))
DETECTION_CONFIDENCE = float(os.getenv("DETECTION_CONFIDENCE"))
DETECTION_IOU = float(os.getenv("DETECTION_IOU"))
DETECTION_SAVE = False
DETECTION_TARGET_WIDTH = int(os.getenv("DETECTION_TARGET_WIDTH"))
DETECTION_TARGET_HEIGHT = int(os.getenv("DETECTION_TARGET_HEIGHT"))

# OCR設定
OCR_MODEL = os.getenv("OCR_MODEL")
OCR_IMG_SIZE = int(os.getenv("OCR_IMG_SIZE"))
OCR_CONFIDENCE = float(os.getenv("OCR_CONFIDENCE"))
OCR_IOU = float(os.getenv("OCR_IOU"))
OCR_SAVE = False
OCR_START_REGION_CODE_CLASS_ID = int(os.getenv("OCR_START_REGION_CODE_CLASS_ID"))
UNDEFINED_TEXT = os.getenv("UNDEFINED_TEXT")

# OUTPUT設定
OUTPUT_CAPTURE_DIR = os.getenv("OUTPUT_CAPTURE_DIR")
OUTPUT_DETECT_DIR = os.getenv("OUTPUT_DETECT_DIR")
OUTPUT_OCR_DIR = os.getenv("OUTPUT_OCR_DIR")
OUTPUT_LOGS_DIR = os.getenv("OUTPUT_LOGS_DIR")
OUTPUT_BUFFER_DIR = os.getenv("OUTPUT_BUFFER_DIR")
ERROR_LOG_FILE_NAME = os.getenv("ERROR_LOG_FILE_NAME")
BUFFER_JSON_FILE_NAME = os.getenv("BUFFER_JSON_FILE_NAME")

# RPI CAM設定
CAMERA_ID = os.getenv("CAMERA_ID")
RPICAM_METERING = os.getenv("RPICAM_METERING")
RPICAM_AUTOFOCUS_MODE = os.getenv("RPICAM_AUTOFOCUS_MODE")
RPICAM_TIMEOUT = int(os.getenv("RPICAM_TIMEOUT"))

# TIME STAMP設定
TIME_STAMP_FORMAT = os.getenv("TIME_STAMP_FORMAT")

# PROXIMITY SENSOR設定
PROXIMITY_SENSOR_THRESHOLD_CM = float(os.getenv("PROXIMITY_SENSOR_THRESHOLD_CM"))
PROXIMITY_SENSOR_TRIGGER_PIN = int(os.getenv("PROXIMITY_SENSOR_TRIGGER_PIN"))
PROXIMITY_SENSOR_ECHO_PIN = int(os.getenv("PROXIMITY_SENSOR_ECHO_PIN"))
PROXIMITY_SENSOR_MAX_DISTANCE_METER = float(os.getenv("PROXIMITY_SENSOR_MAX_DISTANCE_METER"))
PROXIMITY_SENSOR_OUT_OF_RANGE = os.getenv("PROXIMITY_SENSOR_OUT_OF_RANGE")

# DATABASE設定
API_NUMBER_PLATE_DATA_URL = os.getenv("API_NUMBER_PLATE_DATA_URL")
API_ERROR_DATA_URL = os.getenv("API_ERROR_DATA_URL")
API_KEY = os.getenv("API_KEY")
API_NAME = os.getenv("API_NAME")
DB_TIMEOUT_SEC = float(os.getenv("DB_TIMEOUT_SEC"))
RASPBERRY_PI_NUM = os.getenv("RASPBERRY_PI_NUM")

# MAIN設定
MAIN_LOOP_DELAY_SEC = float(os.getenv("MAIN_LOOP_DELAY_SEC"))